"use client";

import React, { useState } from "react";
import { ChevronDown, ChevronUp, Zap, Shield, Trophy, Coins, Wifi, HelpCircle, ExternalLink, MessageCircle } from "lucide-react";
import { cn } from "@/lib/utils";

// ── Types ─────────────────────────────────────────────────────────────────────

interface FAQItem {
  q: string;
  a: string;
}

interface FAQSection {
  icon: React.ReactNode;
  title: string;
  color: string;
  items: FAQItem[];
}

// ── Data ──────────────────────────────────────────────────────────────────────

const FAQ_SECTIONS: FAQSection[] = [
  {
    icon: <Zap className="h-4 w-4" />,
    title: "Getting Started",
    color: "text-yellow-500 bg-yellow-500/10 border-yellow-500/20",
    items: [
      {
        q: "What is PrimeIQ?",
        a: "PrimeIQ is a 1v1 quiz dueling platform built by Faucetdrops on the Celo blockchain. You challenge another player on a topic of your choice, stake, and the winner takes the pool — all settled automatically by a smart contract.",
      },
      {
        q: "What wallet do I need?",
        a: "PrimeIQ runs inside MiniPay (Opera Mini's built-in wallet). Your wallet connects automatically when you open the app — no setup required. Make sure you have some USDm, USDC, or USDT on Celo to stake.",
      },
      {
        q: "How do I create a challenge?",
        a: 'Tap "Create Challenge", enter a topic (e.g. "Ethereum & DeFi basics"), choose your stake amount, set visibility to Public or Private, and hit Launch. An AI generates 15–30 questions across Easy, Medium, and Hard rounds.',
      },
      {
        q: "How do I join a challenge?",
        a: "Browse the public hub to find open challenges, or paste a challenge code/link shared by a friend. Once you join, approve the stake transaction in MiniPay and click Ready to start.",
      },
    ],
  },
  {
    icon: <Coins className="h-4 w-4" />,
    title: "Staking & Payments",
    color: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
    items: [
      {
        q: "Which tokens are supported?",
        a: "USDm, USDC, and USDT on Celo mainnet (chain ID 42220). All are stablecoins pegged to the US dollar, so your stake value doesn't fluctuate.",
      },
      {
        q: "What is the minimum stake?",
        a: "The minimum stake is 0.50 per player (0.50 USDm / USDC / USDT). The winner takes the full combined pool.",
      },
      {
        q: "Is there a fee?",
        a: "Yes — a flat 0.25 token fee per player is charged at stake time to cover gas and platform costs. This is deducted on top of your stake, so budget a little extra.",
      },
      {
        q: "How does the pre-lobby negotiation work?",
        a: "When you enter a challenge's pre-lobby, you can accept the creator's opening stake or propose a different amount. The creator can counter your offer privately, and you can counter back. Once both sides agree, the stake is locked on-chain.",
      },
      {
        q: "When do I get paid if I win?",
        a: "After the game ends, a Claim Reward button appears on the results screen. Tap it to trigger the on-chain claimReward() transaction — funds land in your MiniPay wallet immediately.",
      },
      {
        q: "What happens in a tie?",
        a: "In a perfectly tied game, the smart contract calls refundQuiz() and both players receive their original stake back (minus the flat fee).",
      },
    ],
  },
  {
    icon: <Trophy className="h-4 w-4" />,
    title: "Gameplay",
    color: "text-blue-500 bg-blue-500/10 border-blue-500/20",
    items: [
      {
        q: "How are questions generated?",
        a: "Questions are generated by AI (Gemini 2.5 Flash, with Groq as fallback) based on the topic you provide. Each game has 3 rounds — Easy, Medium, and Hard — with 5–10 questions each.",
      },
      {
        q: "How is scoring calculated?",
        a: "Correct answers earn 500 base points plus up to 500 speed bonus points. Answering instantly earns the full 1000; answering at the last second earns 500. Wrong answers score 0.",
      },
      {
        q: "What are the time limits per round?",
        a: "Easy: 7 seconds per question. Medium: 10 seconds. Hard: 13 seconds.",
      },
      {
        q: "Can I rematch my opponent?",
        a: "Yes — after a game ends, tap Request Rematch. Your opponent has 30 seconds to accept. If they do, a new challenge is created with the same topic and stake.",
      },
    ],
  },
  {
    icon: <Shield className="h-4 w-4" />,
    title: "Security & Smart Contract",
    color: "text-purple-500 bg-purple-500/10 border-purple-500/20",
    items: [
      {
        q: "Is my stake safe?",
        a: "Stakes are held in the PrimeIQ smart contract on Celo. The contract uses ReentrancyGuard and SafeERC20. Funds are only released to the verified winner or refunded in a tie — the platform cannot arbitrarily take funds.",
      },
      {
        q: "What if my opponent disconnects mid-game?",
        a: "There is a 60-second grace period for reconnection. If the opponent doesn't reconnect in time, you win by forfeit and the contract pays out normally.",
      },
      {
        q: "What if the challenge expires before the opponent joins?",
        a: "Challenges expire after 10 minutes of inactivity. You can call emergencyRefund() on-chain to recover your stake after expiry.",
      },
      {
        q: "Who sets the winner on-chain?",
        a: "A resolver wallet (operated by PrimeIQ) calls setWinner() after the game logic confirms a result. This is the only account that can resolve quizzes — it cannot move funds, only designate who can claim.",
      },
    ],
  },
  {
    icon: <Wifi className="h-4 w-4" />,
    title: "Technical Issues",
    color: "text-orange-500 bg-orange-500/10 border-orange-500/20",
    items: [
      {
        q: "My stake transaction failed — what do I do?",
        a: 'If your transaction was signed in MiniPay but the game didn\'t register it, tap "Already staked? Sync my stake" on the lobby screen. This reads your stake directly from the contract and syncs it without needing a new transaction.',
      },
      {
        q: "I staked but the game won't start.",
        a: "Both players must stake AND click Ready before the game starts. Check the lobby — if your status shows \"Stake verified\", just click the Ready button. If it still shows \"Awaiting stake\", try the Sync button.",
      },
      {
        q: "The app shows 'Permission denied' when trying to transact.",
        a: "This usually means MiniPay hasn't authorized the transaction yet. Close and reopen the app inside MiniPay (not a regular browser), then try again. Make sure you have enough balance including the 0.25 fee.",
      },
      {
        q: "The lobby isn't updating / I can't see my opponent.",
        a: "Tap the refresh icon (↻) in the top-left of the lobby screen to manually pull the latest state. If that doesn't help, close and reopen the challenge link.",
      },
    ],
  },
];

// ── FAQ Accordion Item ────────────────────────────────────────────────────────

function FAQAccordion({ items }: { items: FAQItem[] }) {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <div className="space-y-2">
      {items.map((item, i) => (
        <div
          key={i}
          className={cn(
            "rounded-2xl border transition-all duration-200 overflow-hidden",
            open === i
              ? "border-primary/30 bg-primary/5"
              : "border-border bg-card hover:border-primary/20",
          )}
        >
          <button
            onClick={() => setOpen(open === i ? null : i)}
            className="w-full flex items-start justify-between gap-3 px-4 py-3.5 text-left"
          >
            <span className="text-sm font-bold text-foreground leading-snug flex-1">{item.q}</span>
            <span className="shrink-0 mt-0.5 text-muted-foreground">
              {open === i
                ? <ChevronUp className="h-4 w-4" />
                : <ChevronDown className="h-4 w-4" />
              }
            </span>
          </button>
          {open === i && (
            <div className="px-4 pb-4">
              <p className="text-sm text-muted-foreground leading-relaxed">{item.a}</p>
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export default function SupportPage() {
  return (
    <div className="min-h-screen bg-background">

      {/* Header */}
      <div className="border-b border-border bg-card/50 backdrop-blur-md sticky top-0 z-20">
  <div className="max-w-2xl mx-auto px-4 h-14 flex items-center gap-3">
    <button
      onClick={() => window.history.back()}
      className="flex items-center justify-center w-8 h-8 rounded-xl border border-border bg-card hover:bg-muted transition-colors active:scale-95 shrink-0"
    >
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M19 12H5M12 19l-7-7 7-7"/>
      </svg>
    </button>
    <HelpCircle className="h-5 w-5 text-primary shrink-0" />
    <h1 className="font-black text-foreground text-base">Support & FAQ</h1>
  </div>
</div>

      <div className="max-w-2xl mx-auto px-4 py-8 pb-24 space-y-10">

        {/* Hero */}
        <div className="text-center space-y-3 pt-2">
          <div className="text-5xl">🧠</div>
          <div>
            <h2 className="text-2xl font-black text-foreground">How can we help?</h2>
            <p className="text-muted-foreground text-sm mt-1 max-w-xs mx-auto">
              Everything you need to know about PrimeIQ — staking, gameplay, and troubleshooting.
            </p>
          </div>
        </div>

        {/* FAQ Sections */}
        {FAQ_SECTIONS.map((section) => (
          <section key={section.title} className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={cn("flex items-center justify-center w-7 h-7 rounded-xl border text-xs font-black", section.color)}>
                {section.icon}
              </span>
              <h3 className="font-black text-foreground text-base">{section.title}</h3>
            </div>
            <FAQAccordion items={section.items} />
          </section>
        ))}

        {/* Contract info */}
        <div className="rounded-3xl border border-border bg-card overflow-hidden">
          <div className="px-5 py-4 border-b border-border">
            <h3 className="font-black text-foreground text-sm flex items-center gap-2">
              <Shield className="h-4 w-4 text-purple-500" /> Smart Contract
            </h3>
          </div>
          <div className="px-5 py-4 space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div className="flex-1 min-w-0">
                <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1">PrimeIQ Contract (Celo)</p>
                <p className="font-mono text-xs text-foreground break-all">
                  0x9088298cd07BE0cAA1e256d3f3761313e1a1447E
                </p>
              </div>
              <a
                href="https://celoscan.io/address/0x9088298cd07BE0cAA1e256d3f3761313e1a1447E"
                target="_blank"
                rel="noopener noreferrer"
                className="shrink-0 flex items-center gap-1 text-xs font-bold text-primary hover:opacity-70 transition-opacity pt-5"
              >
                View <ExternalLink className="h-3 w-3" />
              </a>
            </div>
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              All stakes are held in this contract. The resolver wallet can only call{" "}
              <code className="bg-muted px-1 rounded text-[10px]">setWinner</code>,{" "}
              <code className="bg-muted px-1 rounded text-[10px]">refundQuiz</code>, and{" "}
              <code className="bg-muted px-1 rounded text-[10px]">setStakePerPlayer</code> — it
              cannot withdraw funds directly. Players always retain the right to call{" "}
              <code className="bg-muted px-1 rounded text-[10px]">emergencyRefund</code> after expiry.
            </p>
          </div>
        </div>

        {/* Contact */}
        <div className="rounded-3xl border-2 border-primary/20 bg-primary/5 p-6 text-center space-y-4">
          <div className="text-3xl">💬</div>
          <div>
            <h3 className="font-black text-foreground">Still need help?</h3>
            <p className="text-sm text-muted-foreground mt-1">
              Reach us directly — we typically respond within a few hours.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-2 justify-center">
            <a
              href="https://t.me/faucetdropschat"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 px-5 py-3 rounded-2xl bg-primary text-primary-foreground font-black text-sm hover:opacity-90 transition-all active:scale-[0.99]"
            >
              <MessageCircle className="h-4 w-4" /> Telegram Support
            </a>
            <a
              href="mailto:drops.faucet@gmail.com"
              className="flex items-center justify-center gap-2 px-5 py-3 rounded-2xl border-2 border-border bg-card text-foreground font-black text-sm hover:bg-muted transition-all active:scale-[0.99]"
            >
              ✉️ Email Us
            </a>
          </div>
        </div>

      </div>
    </div>
  );
}